/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PlayDateLevelRouteImport } from './routes/play.$date.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDateLevelRoute = PlayDateLevelRouteImport.update({
  id: '/play/$date/$level',
  path: '/play/$date/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/play/$date/$level': typeof PlayDateLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/play/$date/$level': typeof PlayDateLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/play/$date/$level': typeof PlayDateLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stats' | '/play/$date/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stats' | '/play/$date/$level'
  id: '__root__' | '/' | '/stats' | '/play/$date/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRoute
  PlayDateLevelRoute: typeof PlayDateLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$date/$level': {
      id: '/play/$date/$level'
      path: '/play/$date/$level'
      fullPath: '/play/$date/$level'
      preLoaderRoute: typeof PlayDateLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRoute,
  PlayDateLevelRoute: PlayDateLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
